PaginationMasPartial/Models/Articulo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaginationMasPartial.Models
{
    [Table("ARTICULOS")]
    public class Articulo
    {
        [Key]
        [Column("Id")]
        public int Id { get; set; }

        [Column("Imagen")]
        public string Imagen { get; set; }

        [Column("Nombre")]
        public string Nombre { get; set; }

        [Column("Precio")]
        public int Precio { get; set; }
    }
}

PaginationMasPartial/Models/ErrorViewModel.cs
namespace PaginationMasPartial.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PaginationMasPartial/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PaginationMasPartial.Models
{
    [Table("USUARIOS")]
    public class Usuario
    {
        [Key]
        [Column("Id")]
        public int Id { get; set; }

        [Column("Nombre")]
        public string Nombre { get; set; }

        [Column("Contrasenia")]
        public string Contrasenia { get; set; }
    }
}

PaginationMasPartial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PaginationMasPartial.Extensions;
using PaginationMasPartial.Models;
using PaginationMasPartial.Repositories;
using System.Diagnostics;

namespace PaginationMasPartial.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private RepositoryUsuarios repo;

        public HomeController(ILogger<HomeController> logger, RepositoryUsuarios repo)
        {
            _logger = logger;
            this.repo = repo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string nombre, string contrasenia)
        {
            Usuario user = this.repo.HacerLogin(nombre, contrasenia);

            if (user == null)
            {
                ViewData["ERROR"] = "bLA";
                return View();
            }
            else
            {
                HttpContext.Session.SetObject("USUARIO", user);
                ViewData["CONECTADO"] = "Estas conectado";
                return View();
                /*return RedirectToAction("ConsultaPaginado","Usuarios");*/
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PaginationMasPartial/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using PaginationMasPartial.Models;
using PaginationMasPartial.Repositories;

namespace PaginationMasPartial.Controllers
{
    public class UsuariosController : Controller
    {
        private RepositoryArticulos repo;

        public UsuariosController(RepositoryArticulos repo)
        {
            this.repo = repo;
        }

        public IActionResult ConsultaPaginado()
        {
            ViewData["TOTAL"] = this.repo.TotalArticulos();
            return View();
        }

        [HttpPost("Usuarios/ConsultaPaginado")]
        [HttpGet("Usuarios/ConsultaPaginado/{posicion}/{registrospagina}")]
        public IActionResult ConsultaPaginado(int registrospagina, int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }

            ViewData["TOTAL"] = this.repo.TotalArticulos();
            ViewData["REGISTROPAGINA"] = registrospagina;

            List<Articulo> articulosxpagina = this.repo.ListaArticulos(registrospagina, posicion.Value);
            return View(articulosxpagina);
        }
    }
}

PaginationMasPartial/ViewComponents/ApartadoLogeadoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PaginationMasPartial.Repositories;

namespace PaginationMasPartial.ViewComponents
{
    public class ApartadoLogeadoViewComponent : ViewComponent
    {
        //AQUI PODRIAMOS TENER CUALQUIER METODO DE UNA CLASE
        //LA PETICION SE REALIZA MEDIANTE EL METODO InvokeAsync
        //ES OBLIGATORIO TENERLO
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

PaginationMasPartial/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@if (Context.Session.GetObject<Usuario>("USUARIO") != null)
{
    <p>Estas conectado</p>
}
else
{
    <form method="post">
        <input type="text" name="nombre" />
        <input type="text" name="contrasenia" />
        <button>Enviar</button>
    </form>
}

PaginationMasPartial/Views/Shared/Components/ApartadoLogeado/Default.cshtml
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="ConsultaPaginado">Paginado Articulos</a>
</li>

PaginationMasPartial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PaginationMasPartial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PaginationMasPartial.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PaginationMasPartial</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (Context.Session.GetObject<Usuario>("USUARIO") != null)
                        {
                            @await Component.InvokeAsync("ApartadoLogeado")
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PaginationMasPartial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PaginationMasPartial/Views/Usuarios/ConsultaPaginado.cshtml
@model List<Articulo>

@{
    int numregistros = 0;
    int numpagina = 1;
    int registrospagina = 0;

    if (ViewData["TOTAL"] != null)
    {
        numregistros = (int)ViewData["TOTAL"];
    }

    if (ViewData["REGISTROPAGINA"] != null)
    {
        registrospagina = (int)ViewData["REGISTROPAGINA"];
    }
}

@if (numregistros > 0 && Model == null)
{
    <form method="post">
        <select name="registrospagina">
            @for (int i = 1; i < numregistros; i++)
            {
                    <option value="@i">@i</option>
            }
        </select>
        <button>Enviar</button>
    </form>
}

@if (Model != null)
{
    @for (int i=1; i <= numregistros; i+=registrospagina)
    {
        <a asp-action="ConsultaPaginado" asp-controller="Usuarios" asp-route-posicion="@i" asp-route-registrospagina="@registrospagina">PAGINA @numpagina</a>
        numpagina++;
    }
    @foreach (Articulo art in Model)
    {
        <p>@art.Nombre</p>
    }
}